name: Java CI

on: [release]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Action Release
      uses: yakuhzi/action-release@v1.2.0
      with:
      # File to upload to the release
        file: target/**.zip
      # Path to changelog file
